### ISSUE TITLE
Shader error in 'Voxelizer'

### ISSUE THREAD

**Issue by AksAman** [keijiro/TestbedHDRP#4] opened 2018-07-04 20:56 UTC
'ConvertSurfaceDataToBSDFData': cannot implicitly convert from 'float2' to 'struct SurfaceData' at Assets/CustomShader/Shaders/VoxelizerFragment.hlsl(73) (on d3d11)

Compiling Vertex program
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR

**Comment by keijiro** [comment] 2018-07-05 02:03
Thanks for reporting. This is a little bit weird because it looks like you're using a different version of Unity or Package.

**Comment by keijiro** [comment] 2018-07-05 02:07
Thanks for reporting. This is a little bit weird because it looks like you're using a different version of Unity or HDRP Package.

Please check the following points:

- Are you using Unity 2018.2? It's only supported on 2018.2 or later.
- Is HDRP version 2.0.4 is correctly loaded? You can check from Package Manager (Window -> Package Manager).

**Comment by keijiro** [comment] 2018-07-11 01:30
I'm closing this case. Please feel free to reopen if the issue still reproduces.

**Closed by keijiro** 2018-07-11 01:30 UTC
Labels: question
